// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpF4UrRuhxgI9y4gctY_kkfPGptwEoYY0',
    appId: '1:760322055702:android:615ae8d988a280a2861f37',
    messagingSenderId: '760322055702',
    projectId: 'museu-das-mulheres---app',
    storageBucket: 'museu-das-mulheres---app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXyuhQMqAxoBjkz8kYTZhna0FaaOyWVw',
    appId: '1:760322055702:ios:96207031a24c7fc4861f37',
    messagingSenderId: '760322055702',
    projectId: 'museu-das-mulheres---app',
    storageBucket: 'museu-das-mulheres---app.firebasestorage.app',
    androidClientId: '760322055702-esqe4gabos4a1893eu2abpg2onjlhrm3.apps.googleusercontent.com',
    iosClientId: '760322055702-f64oj0t8vkpb7fi1fvv9e9joe5gm85lv.apps.googleusercontent.com',
    iosBundleId: 'com.mrblab.travelhourapp',
  );

}